#! /bin/bash

export LD_LIBRARY_PATH="$HOME/lib"
export AFEPACK_PATH="$HOME/src/AFEPack"
export AFEPACK_TEMPLATE_PATH="$AFEPACK_PATH/template/interval:$AFEPACK_PATH/template/triangle:$AFEPACK_PATH/template/twin_triangle"

N=$1
shift
mpiexec -np ${N} ./main $*

